name: Deploy to Production

on:
  push:
    branches:
      - main # change if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 64.227.115.119
          username: seif
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apps/hire-space/app
            git pull origin main
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm i
            npm run build
            pm2 restart hire-space
